services:
  node:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: node.Dockerfile

  nginx:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "8321:80"
